// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Context;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20221202111919_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebAPI.Models.Anggota", b =>
                {
                    b.Property<string>("KodeAnggota")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlamatAnggota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JenisKelamin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pekerjaan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telepon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TempatLahir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TglEntry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglLahir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglMasuk")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEntry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeAnggota");

                    b.ToTable("Anggota");
                });

            modelBuilder.Entity("WebAPI.Models.Angsuran", b =>
                {
                    b.Property<int>("KodeAngsuran")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KodeAngsuran"), 1L, 1);

                    b.Property<int>("BesarAngsuran")
                        .HasColumnType("int");

                    b.Property<int>("Denda")
                        .HasColumnType("int");

                    b.Property<string>("KodeAnggota")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KodePinjaman")
                        .HasColumnType("int");

                    b.Property<int>("SisaPinjaman")
                        .HasColumnType("int");

                    b.Property<DateTime>("TglEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEntry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeAngsuran");

                    b.HasIndex("KodeAnggota");

                    b.HasIndex("KodePinjaman");

                    b.ToTable("Angsuran");
                });

            modelBuilder.Entity("WebAPI.Models.JenisPinjaman", b =>
                {
                    b.Property<string>("KodeJenisPinjaman")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Bunga")
                        .HasColumnType("float");

                    b.Property<int>("LamaAngsuran")
                        .HasColumnType("int");

                    b.Property<double>("MaksPinjaman")
                        .HasColumnType("float");

                    b.Property<string>("NamaPinjaman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TglEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEntry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeJenisPinjaman");

                    b.ToTable("JenisPinjaman");
                });

            modelBuilder.Entity("WebAPI.Models.JenisSimpanan", b =>
                {
                    b.Property<string>("KodeJenisSimpanan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("BesarSimpanan")
                        .HasColumnType("float");

                    b.Property<string>("NamaSimpanan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TglEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEntry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeJenisSimpanan");

                    b.ToTable("JenisSimpanan");
                });

            modelBuilder.Entity("WebAPI.Models.Penarikan", b =>
                {
                    b.Property<int>("KodePenarikan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KodePenarikan"), 1L, 1);

                    b.Property<int>("BesarPenarikan")
                        .HasColumnType("int");

                    b.Property<int>("KodeTabungan")
                        .HasColumnType("int");

                    b.Property<DateTime>("TglPenarikan")
                        .HasColumnType("datetime2");

                    b.HasKey("KodePenarikan");

                    b.HasIndex("KodeTabungan");

                    b.ToTable("Penarikan");
                });

            modelBuilder.Entity("WebAPI.Models.Pengajuan", b =>
                {
                    b.Property<int>("KodePengajuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KodePengajuan"), 1L, 1);

                    b.Property<int>("BesarPinjaman")
                        .HasColumnType("int");

                    b.Property<string>("KodeAnggota")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KodeJenisPinjaman")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TglAcc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglPengajuan")
                        .HasColumnType("datetime2");

                    b.HasKey("KodePengajuan");

                    b.HasIndex("KodeAnggota");

                    b.HasIndex("KodeJenisPinjaman");

                    b.ToTable("Pengajuan");
                });

            modelBuilder.Entity("WebAPI.Models.Pinjaman", b =>
                {
                    b.Property<int>("KodePinjaman")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KodePinjaman"), 1L, 1);

                    b.Property<double>("BesarAngsuran")
                        .HasColumnType("float");

                    b.Property<double>("BesarPinjaman")
                        .HasColumnType("float");

                    b.Property<string>("KodeJenisPinjaman")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LamaAngsuran")
                        .HasColumnType("int");

                    b.Property<int>("SisaAngsuran")
                        .HasColumnType("int");

                    b.Property<double>("SisaPinjaman")
                        .HasColumnType("float");

                    b.Property<DateTime>("TglEntry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglTempo")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEntry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodePinjaman");

                    b.HasIndex("KodeJenisPinjaman");

                    b.ToTable("Pinjaman");
                });

            modelBuilder.Entity("WebAPI.Models.Simpanan", b =>
                {
                    b.Property<int>("KodeSimpanan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KodeSimpanan"), 1L, 1);

                    b.Property<double>("BesarSimpanan")
                        .HasColumnType("float");

                    b.Property<string>("KodeAnggota")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KodeJenisSimpanan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TglEntry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglMulai")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEntry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeSimpanan");

                    b.HasIndex("KodeAnggota");

                    b.HasIndex("KodeJenisSimpanan");

                    b.ToTable("Simpanan");
                });

            modelBuilder.Entity("WebAPI.Models.Tabungan", b =>
                {
                    b.Property<int>("KodeTabungan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KodeTabungan"), 1L, 1);

                    b.Property<double>("BesarTabungan")
                        .HasColumnType("float");

                    b.Property<string>("KodeAnggota")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TglMulai")
                        .HasColumnType("datetime2");

                    b.HasKey("KodeTabungan");

                    b.HasIndex("KodeAnggota");

                    b.ToTable("Tabungan");
                });

            modelBuilder.Entity("WebAPI.Models.User", b =>
                {
                    b.Property<string>("KodeUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TglEntry")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KodeUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI.Models.Angsuran", b =>
                {
                    b.HasOne("WebAPI.Models.Anggota", "Anggota")
                        .WithMany()
                        .HasForeignKey("KodeAnggota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.Pinjaman", "Pinjaman")
                        .WithMany()
                        .HasForeignKey("KodePinjaman")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anggota");

                    b.Navigation("Pinjaman");
                });

            modelBuilder.Entity("WebAPI.Models.Penarikan", b =>
                {
                    b.HasOne("WebAPI.Models.Tabungan", "Tabungan")
                        .WithMany()
                        .HasForeignKey("KodeTabungan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tabungan");
                });

            modelBuilder.Entity("WebAPI.Models.Pengajuan", b =>
                {
                    b.HasOne("WebAPI.Models.Anggota", "Anggota")
                        .WithMany()
                        .HasForeignKey("KodeAnggota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.JenisPinjaman", "JenisPinjaman")
                        .WithMany()
                        .HasForeignKey("KodeJenisPinjaman")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anggota");

                    b.Navigation("JenisPinjaman");
                });

            modelBuilder.Entity("WebAPI.Models.Pinjaman", b =>
                {
                    b.HasOne("WebAPI.Models.JenisPinjaman", "JenisPinjaman")
                        .WithMany()
                        .HasForeignKey("KodeJenisPinjaman")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JenisPinjaman");
                });

            modelBuilder.Entity("WebAPI.Models.Simpanan", b =>
                {
                    b.HasOne("WebAPI.Models.Anggota", "Anggota")
                        .WithMany()
                        .HasForeignKey("KodeAnggota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPI.Models.JenisPinjaman", "JenisSimpanan")
                        .WithMany()
                        .HasForeignKey("KodeJenisSimpanan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anggota");

                    b.Navigation("JenisSimpanan");
                });

            modelBuilder.Entity("WebAPI.Models.Tabungan", b =>
                {
                    b.HasOne("WebAPI.Models.Anggota", "Anggota")
                        .WithMany()
                        .HasForeignKey("KodeAnggota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anggota");
                });
#pragma warning restore 612, 618
        }
    }
}
